version: "3"

services:
  php:
    build: docker/php
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s docker/entrypoint.sh
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - network
    depends_on:
      - mysql
      - redis

  nginx:
    build: docker/nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - network
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    # command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - network

networks:
  network:
    driver: bridge
