version: "3"

volumes:
  # MYSQL
  sysbt-mysql-data:
    driver: local
  # REDIS
  sysbt-redis-data:
    driver: local

networks:
  network:
    driver: bridge

services:
  php:
    image: roberto0arruda/php-fpm
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.18-alpine
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    # command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - sysbt-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - network

  redis:
    image: redis:alpine
    volumes:
      - sysbt-redis-data:/data
    expose:
      - 6379
    networks:
      - network
